packages:
  - "apps/*"
  - "packages/*"
  - "liquid-staking-protocol-ui"
  - "contract/liquid-staking-protocol-contract"
  - "liquid-staking-protocol-server"
  - "liquid-staking-api"
  - "liquid-staking-cli"
